#!/bin/sh

echo "Creating Virtual Env"
python3 -m venv venv

echo "Activating Virtual Env"
source venv/bin/activate

echo "Dependencies"
pip install -r requirements.txt

echo "Flush Database"
python manage.py flush --noinput

echo "Apply Migrations"
python manage.py migrate

echo "Loading Test Data"
python manage.py loaddata seed_data
